version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.0
         environment:
           RAILS_ENV: test
       - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
        
      - run: bundle exec rake db:create db:schema:load --trace

      - run:
          name: run tests
          command: |
            bundle exec rails test
