# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Type.create(name: 'オーケストラ')
Type.create(name: '吹奏楽')
Type.create(name: 'アンサンブル')
Type.create(name: '合唱')
Type.create(name: '大編成')
Type.create(name: 'サブカル系')
Type.create(name: '音大生多数')
Type.create(name: 'プロ多数')

Region.create(name: '東京都内', sort_number: 1)
Region.create(name: '関東甲信越', sort_number: 2)
Region.create(name: '北海道・東北', sort_number: 3)
Region.create(name: '中部', sort_number: 4)
Region.create(name: '近畿', sort_number: 5)
Region.create(name: '中国・四国', sort_number: 6)
Region.create(name: '九州', sort_number: 7)
Region.create(name: '海外', sort_number: 10)

InstrumentCategory.create(name: '木管楽器')
InstrumentCategory.create(name: '金管楽器')
InstrumentCategory.create(name: '弦楽器')
InstrumentCategory.create(name: '打楽器')
InstrumentCategory.create(name: '声楽')
InstrumentCategory.create(name: 'その他')

Instrument.create(name: 'フルート', sort_number: 111, short_name: 'Fl', instrument_category_id: 1)
Instrument.create(name: 'ピッコロ', sort_number: 112, short_name: 'Picc', instrument_category_id: 1)
Instrument.create(name: 'オーボエ', sort_number: 121, short_name: 'Ob', instrument_category_id: 1)
Instrument.create(name: 'クラリネット', sort_number: 131, short_name: 'Cl', instrument_category_id: 1)
Instrument.create(name: 'ファゴット', sort_number: 141, short_name: 'Fg', instrument_category_id: 1)
Instrument.create(name: 'ソプラノサックス', sort_number: 151, short_name: 'S.Sax', instrument_category_id: 1)
Instrument.create(name: 'アルトサックス', sort_number: 152, short_name: 'A.Sax', instrument_category_id: 1)
Instrument.create(name: 'テナーサックス', sort_number: 153, short_name: 'T.Sax', instrument_category_id: 1)
Instrument.create(name: 'バリトンサックス', sort_number: 154, short_name: 'B.Sax', instrument_category_id: 1)
Instrument.create(name: 'ホルン', sort_number: 211, short_name: 'Hr', instrument_category_id: 2)
Instrument.create(name: 'トランペット', sort_number: 221, short_name: 'Tp', instrument_category_id: 2)
Instrument.create(name: 'トロンボーン', sort_number: 231, short_name: 'Tb', instrument_category_id: 2)
Instrument.create(name: 'ユーフォニアム', sort_number: 232, short_name: 'Euph', instrument_category_id: 2)
Instrument.create(name: 'チューバ', sort_number: 241, short_name: 'Tu', instrument_category_id: 2)
Instrument.create(name: 'ヴァイオリン', sort_number: 311, short_name: 'Vn', instrument_category_id: 3)
Instrument.create(name: '1stヴァイオリン', sort_number: 312, short_name: '1stVn', instrument_category_id: 3)
Instrument.create(name: '2stヴァイオリン', sort_number: 313, short_name: '2ndVn', instrument_category_id: 3)
Instrument.create(name: 'ヴィオラ', sort_number: 321, short_name: 'Va', instrument_category_id: 3)
Instrument.create(name: 'チェロ', sort_number: 331, short_name: 'Vc', instrument_category_id: 3)
Instrument.create(name: 'コントラバス', sort_number: 341, short_name: 'Cb', instrument_category_id: 3)
Instrument.create(name: 'パーカッション', sort_number: 411, short_name: 'Perc', instrument_category_id: 4)
Instrument.create(name: 'ティンパニ', sort_number: 421, short_name: 'Temp', instrument_category_id: 4)
Instrument.create(name: 'スネアドラム', sort_number: 422, short_name: 'SD', instrument_category_id: 4)
Instrument.create(name: 'バスドラム', sort_number: 423, short_name: 'BD', instrument_category_id: 4)
Instrument.create(name: 'シンバル', sort_number: 431, short_name: 'Sym', instrument_category_id: 4)
Instrument.create(name: 'トライアングル', sort_number: 432, short_name: 'Tr', instrument_category_id: 4)
Instrument.create(name: 'ドラ', sort_number: 433, short_name: 'Tam-tam', instrument_category_id: 4)
Instrument.create(name: 'ソプラノ', sort_number: 511, short_name: 'Sop', instrument_category_id: 5)
Instrument.create(name: 'アルト', sort_number: 512, short_name: 'Alt', instrument_category_id: 5)
Instrument.create(name: 'テナー', sort_number: 513, short_name: 'Ten', instrument_category_id: 5)
Instrument.create(name: 'バス', sort_number: 514, short_name: 'Bass', instrument_category_id: 5)
Instrument.create(name: '指揮者', sort_number: 611, short_name: 'Cond', instrument_category_id: 6)
Instrument.create(name: '編曲者', sort_number: 621, short_name: 'Arr', instrument_category_id: 6)

Hole.create(name: 'サントリーホール', address:'東京都港区赤坂1-13-1', url: 'https://www.suntory.co.jp/suntoryhall/', region: Region.find_by(name: '東京都内'))
Hole.create(name: '東京芸術劇場', address:'東京都豊島区西池袋1-8-1', url: 'http://www.geigeki.jp/', region: Region.find_by(name: '東京都内'))

Conductor.create(name: '小林研一郎', description: '炎のコバケン', url: 'http://www.it-japan.co.jp/kobaken/index2.htm')

Country.create(name: 'ドイツ', description: 'バッハ、ベートーヴェン、ブラームスとか')
Country.create(name: 'ロシア', description: 'チャイコフスキー、ショスタコーヴィチとか')
Country.create(name: 'フランス', description: 'ラヴェル、サン=サーンスとか')
Country.create(name: '日本', description: '武満徹、伊福部昭とか')

Composer.create(display_name: 'ブラームス', full_name: 'ヨハネス・ブラームス', description: 'ドイツ三大Bのうちの一人', countries: [Country.find_by(name: 'ドイツ')])
Composer.create(display_name: 'チャイコフスキー', full_name: 'ピョートル・チャイコフスキー', description: 'ロシアを代表するメロディーメーカー', countries: [Country.find_by(name: 'ロシア')])

Tune.create(title: '交響曲第1番 ハ短調 op.68', description: 'ブラームスの初めての交響曲', composer: Composer.find_by(display_name: 'ブラームス'))
Tune.create(title: '交響曲第2番 ニ長調 op.73', description: 'ブラームスの２番目の交響曲', composer: Composer.find_by(display_name: 'ブラームス'))
Tune.create(title: '交響曲第3番 ヘ長調 op.90', description: 'ブラームスの３番目の交響曲', composer: Composer.find_by(display_name: 'ブラームス'))
Tune.create(title: '交響曲第4番 ホ短調 op.98', description: 'ブラームスの４番目の交響曲', composer: Composer.find_by(display_name: 'ブラームス'))
Tune.create(title: '交響曲第1番 ト短調 op.13「冬の日の幻想」', description: 'チャイコフスキー初めての交響曲', composer: Composer.find_by(display_name: 'チャイコフスキー'))
Tune.create(title: '交響曲第2番 ハ短調 op.17「小ロシア」', description: 'チャイコフスキー２番目の交響曲', composer: Composer.find_by(display_name: 'チャイコフスキー'))

Solist.create(name: '北村源三', url: 'https://ja.wikipedia.org/wiki/%E5%8C%97%E6%9D%91%E6%BA%90%E4%B8%89', description: '元NHK交響楽団首席トランペット奏者', instrument: Instrument.find_by(name: 'トランペット'))

CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "フルート")], canonical_route: CanonicalRoute.create(canonical_id: 'fl', canonical_model_name: 'instruments', label: 'フルート', category: 'instrument', order_in_Category: 1, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "オーボエ")], canonical_route: CanonicalRoute.create(canonical_id: 'ob', canonical_model_name: 'instruments', label: 'オーボエ', category: 'instrument', order_in_Category: 2, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "クラリネット")], canonical_route: CanonicalRoute.create(canonical_id: 'cl', canonical_model_name: 'instruments', label: 'クラリネット', category: 'instrument', order_in_Category: 3, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "ファゴット")], canonical_route: CanonicalRoute.create(canonical_id: 'fg', canonical_model_name: 'instruments', label: 'ファゴット', category: 'instrument', order_in_Category: 4, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "ホルン")], canonical_route: CanonicalRoute.create(canonical_id: 'hr', canonical_model_name: 'instruments', label: 'ホルン', category: 'instrument', order_in_Category: 5, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "トランペット")], canonical_route: CanonicalRoute.create(canonical_id: 'tp', canonical_model_name: 'instruments', label: 'トランペット', category: 'instrument', order_in_Category: 6, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "トロンボーン")], canonical_route: CanonicalRoute.create(canonical_id: 'tb', canonical_model_name: 'instruments', label: 'トロンボーン', category: 'instrument', order_in_Category: 7, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "チューバ")], canonical_route: CanonicalRoute.create(canonical_id: 'tu', canonical_model_name: 'instruments', label: 'チューバ', category: 'instrument', order_in_Category: 8, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "パーカッション")], canonical_route: CanonicalRoute.create(canonical_id: 'perc', canonical_model_name: 'instruments', label: 'パーカッション', category: 'instrument', order_in_Category: 9, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteInstrumentsForRecruit.create(instruments: [Instrument.find_by(name: "フルート"), Instrument.find_by(name: "ピッコロ")], canonical_route: CanonicalRoute.create(canonical_id: 'flpicc', canonical_model_name: 'instruments', label: 'フルート・ピッコロ', category: 'multi-instruments', order_in_Category: 1, is_listed_on_top: true, is_listed_on_model_top: true))

CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '東京都内'), canonical_route: CanonicalRoute.create(canonical_id: 'tokyo', canonical_model_name: 'regions', label: '東京都内', category: 'region', order_in_Category: 1, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '関東甲信越'), canonical_route: CanonicalRoute.create(canonical_id: 'kanto', canonical_model_name: 'regions', label: '関東甲信越', category: 'region', order_in_Category: 2, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '北海道・東北'), canonical_route: CanonicalRoute.create(canonical_id: 'hokkaido-tohoku', canonical_model_name: 'regions', label: '北海道・東北', category: 'region', order_in_Category: 3, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '中部'), canonical_route: CanonicalRoute.create(canonical_id: 'chubu', label: '中部', canonical_model_name: 'regions', category: 'region', order_in_Category: 4, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '近畿'), canonical_route: CanonicalRoute.create(canonical_id: 'kinki', label: '近畿', canonical_model_name: 'regions', category: 'region', order_in_Category: 5, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '中国・四国'), canonical_route: CanonicalRoute.create(canonical_id: 'tyugoku-shikoku', canonical_model_name: 'regions', label: '中国・四国', category: 'region', order_in_Category: 5, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '九州'), canonical_route: CanonicalRoute.create(canonical_id: 'kyushu', label: '九州', canonical_model_name: 'regions', category: 'region', order_in_Category: 6, is_listed_on_top: true, is_listed_on_model_top: true))
CanonicalRouteRegionForRecruit.create(region: Region.find_by(name: '海外'), canonical_route: CanonicalRoute.create(canonical_id: 'overseas', label: '海外', canonical_model_name: 'regions', category: 'region', order_in_Category: 10, is_listed_on_top: true, is_listed_on_model_top: true))

Concert.create(title: 'title', date: Date.new, doors_open: Date.new, cirtain_time: Date.new,description: 'hoge', team: Team.first, hole_id: 1, conductor_ids: [1])
Repertoire.create(arranger: 'アレンジャー', description: '曲の 説明', concert: Concert.first, tune: Tune.first, solist_ids: [1])


